# Generated by Django 5.2.17 on 2026-09-01 16:13

import django.core.validators
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.CharField(max_length=320)),
                ('description', models.TextField()),
                ('venue_name', models.CharField(max_length=180)),
                ('venue_address', models.TextField()),
                ('timezone', models.CharField(default='Africa/Johannesburg', max_length=64, validators=[events.models.validate_timezone])),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='ZAR', editable=False, max_length=3)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_at', 'title'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='event_end_after_start'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='event_capacity_positive'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='event_price_non_negative'), models.CheckConstraint(condition=models.Q(('currency', 'ZAR')), name='event_currency_zar')],
            },
        ),
    ]
