# Generated by Django 5.2.17 on 2026-09-01 16:58

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a JPG, PNG, WebP, or GIF image up to 8 MB.', upload_to='events/%Y/%m/', validators=[events.models.validate_image_size]),
        ),
    ]
