# Generated by Django 5.2.17 on 2026-09-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='payfast', editable=False, max_length=24)),
                ('provider_transaction_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZAR', editable=False, max_length=3)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='initialized', max_length=16)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_digest', models.CharField(max_length=64, unique=True)),
                ('provider_transaction_reference', models.CharField(blank=True, max_length=64)),
                ('payment_status', models.CharField(blank=True, max_length=32)),
                ('merchant_payment_reference', models.CharField(blank=True, max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('source_valid', models.BooleanField(default=False)),
                ('amount_valid', models.BooleanField(default=False)),
                ('server_confirmation_valid', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=240)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
